export const intents = {
  greetings: [
    "hello",
    "hi",
    "hii",
    "helloo",
    "hellow",
    "hey",
    "greetings",
    "good morning",
    "good afternoon",
    "good evening",
    "what's up",
    "sup",
    "ssup",
    "howdy",
  ],
  shipmentTracking: [
    "kidhr",
    "kidhar",
    "track",
    "ship",
    "tracker",
    "shipping",
    "where",
    "where is ship",
    "shipment",
    "order",
    "delivery",
    "parcel",
    "track order",
    "shipment status",
    "status",
    "updates",
    "where is my package",
    "where",
    "package",
    "where is my order",
  ],
  weather: [
    "weather",
    "mausam",
    "temp",
    "forecast",
    "climate",
    "temperature",
    "rain",
    "sunny",
    "cold",
    "hot",
    "rain",
    "storm",
    "stormy",
    "sky",
    "skies",
    "cloud",
    "clouds",
    "cloudy",
    "rainy",
    "winds",
    "wind",
    "windy",
    "is it going to rain",
  ],
  help: [
    "help",
    "?",
    "support",
    "pls help",
    "assist",
    "guidance",
    "assistance",
    "i need help",
    "can you help me",
    "what can you do",
    "what do you do",
  ],
  returnPolicy: [
    "return policy",
    "policy",
    "refunding",
    "refund",
    "return",
    "returns",
    "money back",
    "exchange",
    "return an item",
    "how do i return",
    "can i get a refund",
  ],
  billing: [
    "bill",
    "invoice",
    "billing",
    "payment",
    "receipt",
    "amount",
    "charges",
    "how much",
  ],
  supportContact: [
    "contact support",
    "support",
    "support email",
    "customer service",
    "help desk",
    "phone number",
    "how do i reach",
  ],
  productInquiry: [
    "product details",
    "features",
    "specifications",
    "info about product",
    "item",
    "description",
  ],
  feedback: [
    "feedback",
    "suggestion",
    "complain",
    "complaint",
    "reviews",
    "critique",
    "problem",
  ],

};
