export const intents = {
  greetings: [
    "hello",
    "hi",
    "hey",
    "greetings",
    "good morning",
    "good afternoon",
    "good evening",
    "what's up",
    "howdy",
  ],
  shipmentTracking: [
    "track",
    "shipment",
    "order",
    "delivery",
    "parcel",
    "track order",
    "shipment status",
    "where is my package",
    "where is my order",
  ],
  weather: [
    "weather",
    "forecast",
    "climate",
    "temperature",
    "rain",
    "sunny",
    "cold",
    "hot",
    "is it going to rain",
  ],
  help: [
    "help",
    "support",
    "assist",
    "guidance",
    "assistance",
    "i need help",
    "can you help me",
    "what can you do",
  ],
  returnPolicy: [
    "return policy",
    "refund",
    "returns",
    "money back",
    "exchange",
    "return an item",
    "how do i return",
    "can i get a refund",
  ],
};
